# Generated by Django 6.1 on 2026-08-29 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('baseline', 'baseline'), ('advanced', 'advanced')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('completed', 'completed'), ('failed', 'failed')], default='pending', max_length=16)),
                ('patient_profile', models.JSONField(default=dict)),
                ('records', models.JSONField(default=list)),
                ('handover', models.TextField()),
                ('engine_meta', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(max_length=64)),
                ('importance', models.CharField(max_length=16)),
                ('status', models.CharField(max_length=32)),
                ('summary', models.TextField()),
                ('evidence_sources', models.JSONField(blank=True, default=list)),
                ('original_data', models.JSONField(default=dict)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='handovers.analysis')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FindingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('accepted', 'accepted'), ('rejected', 'rejected'), ('edited', 'edited')], max_length=16)),
                ('comment', models.TextField(blank=True, default='')),
                ('edited_summary', models.TextField(blank=True, default='')),
                ('edited_category', models.CharField(blank=True, default='', max_length=64)),
                ('edited_importance', models.CharField(blank=True, default='', max_length=16)),
                ('edited_status', models.CharField(blank=True, default='', max_length=32)),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
                ('finding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='handovers.finding')),
            ],
        ),
    ]
